# TCL File Generated by Component Editor 12.1
# Sat Mar 16 15:51:41 EDT 2013
# DO NOT MODIFY


# 
# lab3_vga "lab3_vga" v1.0
# null 2013.03.16.15:51:41
# 
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module lab3_vga
# 
set_module_property NAME lab3_vga
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME lab3_vga
set_module_property TOP_LEVEL_HDL_FILE lab3_vga.vhd
set_module_property TOP_LEVEL_HDL_MODULE lab3_vga
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME lab3_vga
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file lab3_vga.vhd {SYNTHESIS SIMULATION}
add_file de2_vga_raster.vhd {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink CLOCK_27 clk Input 1


# 
# connection point clock_sink_1
# 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0
set_interface_property clock_sink_1 ENABLED true

add_interface_port clock_sink_1 CLOCK_50 clk Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end AUD_ADCDAT export Input 1
add_interface_port conduit_end AUD_ADCLRCK export Bidir 1
add_interface_port conduit_end AUD_BCLK export Bidir 1
add_interface_port conduit_end AUD_DACDAT export Output 1
add_interface_port conduit_end AUD_DACLRCK export Bidir 1
add_interface_port conduit_end AUD_XCK export Output 1
add_interface_port conduit_end DRAM_ADDR export Output 12
add_interface_port conduit_end DRAM_BA_0 export Output 1
add_interface_port conduit_end DRAM_BA_1 export Output 1
add_interface_port conduit_end DRAM_CAS_N export Output 1
add_interface_port conduit_end DRAM_CKE export Output 1
add_interface_port conduit_end DRAM_CLK export Output 1
add_interface_port conduit_end DRAM_CS_N export Output 1
add_interface_port conduit_end DRAM_DQ export Bidir 16
add_interface_port conduit_end DRAM_LDQM export Output 1
add_interface_port conduit_end DRAM_RAS_N export Output 1
add_interface_port conduit_end DRAM_UDQM export Output 1
add_interface_port conduit_end DRAM_WE_N export Output 1
add_interface_port conduit_end ENET_CLK export Output 1
add_interface_port conduit_end ENET_CMD export Output 1
add_interface_port conduit_end ENET_CS_N export Output 1
add_interface_port conduit_end ENET_DATA export Bidir 16
add_interface_port conduit_end ENET_INT export Input 1
add_interface_port conduit_end ENET_RD_N export Output 1
add_interface_port conduit_end ENET_RST_N export Output 1
add_interface_port conduit_end ENET_WR_N export Output 1
add_interface_port conduit_end EXT_CLOCK export Input 1
add_interface_port conduit_end FL_ADDR export Output 22
add_interface_port conduit_end FL_CE_N export Output 1
add_interface_port conduit_end FL_DQ export Bidir 8
add_interface_port conduit_end FL_OE_N export Output 1
add_interface_port conduit_end FL_RST_N export Output 1
add_interface_port conduit_end FL_WE_N export Output 1
add_interface_port conduit_end GPIO_0 export Bidir 36
add_interface_port conduit_end GPIO_1 export Bidir 36
add_interface_port conduit_end HEX0 export Output 7
add_interface_port conduit_end HEX1 export Output 7
add_interface_port conduit_end HEX2 export Output 7
add_interface_port conduit_end HEX3 export Output 7
add_interface_port conduit_end HEX4 export Output 7
add_interface_port conduit_end HEX5 export Output 7
add_interface_port conduit_end HEX6 export Output 7
add_interface_port conduit_end HEX7 export Output 7
add_interface_port conduit_end I2C_SCLK export Output 1
add_interface_port conduit_end I2C_SDAT export Bidir 1
add_interface_port conduit_end IRDA_RXD export Input 1
add_interface_port conduit_end KEY export Input 4
add_interface_port conduit_end LCD_BLON export Output 1
add_interface_port conduit_end LCD_DATA export Bidir 8
add_interface_port conduit_end LCD_EN export Output 1
add_interface_port conduit_end LCD_ON export Output 1
add_interface_port conduit_end LCD_RS export Output 1
add_interface_port conduit_end LCD_RW export Output 1
add_interface_port conduit_end LEDG export Output 9
add_interface_port conduit_end LEDR export Output 18
add_interface_port conduit_end OTG_ADDR export Output 2
add_interface_port conduit_end OTG_CS_N export Output 1
add_interface_port conduit_end OTG_DACK0_N export Output 1
add_interface_port conduit_end OTG_DACK1_N export Output 1
add_interface_port conduit_end OTG_DATA export Bidir 16
add_interface_port conduit_end OTG_DREQ0 export Input 1
add_interface_port conduit_end OTG_DREQ1 export Input 1
add_interface_port conduit_end OTG_FSPEED export Output 1
add_interface_port conduit_end OTG_INT0 export Input 1
add_interface_port conduit_end OTG_INT1 export Input 1
add_interface_port conduit_end OTG_LSPEED export Output 1
add_interface_port conduit_end OTG_RD_N export Output 1
add_interface_port conduit_end OTG_RST_N export Output 1
add_interface_port conduit_end OTG_WR_N export Output 1
add_interface_port conduit_end PS2_CLK export Input 1
add_interface_port conduit_end PS2_DAT export Input 1
add_interface_port conduit_end SD_CLK export Output 1
add_interface_port conduit_end SD_CMD export Bidir 1
add_interface_port conduit_end SD_DAT export Bidir 1
add_interface_port conduit_end SD_DAT3 export Bidir 1
add_interface_port conduit_end SRAM_ADDR export Output 18
add_interface_port conduit_end SRAM_CE_N export Output 1
add_interface_port conduit_end SRAM_DQ export Bidir 16
add_interface_port conduit_end SRAM_LB_N export Output 1
add_interface_port conduit_end SRAM_OE_N export Output 1
add_interface_port conduit_end SRAM_UB_N export Output 1
add_interface_port conduit_end SRAM_WE_N export Output 1
add_interface_port conduit_end SW export Input 18
add_interface_port conduit_end TCK export Input 1
add_interface_port conduit_end TCS export Input 1
add_interface_port conduit_end TD_DATA export Input 8
add_interface_port conduit_end TD_HS export Input 1
add_interface_port conduit_end TD_RESET export Output 1
add_interface_port conduit_end TD_VS export Input 1
add_interface_port conduit_end TDI export Input 1
add_interface_port conduit_end TDO export Output 1
add_interface_port conduit_end UART_RXD export Input 1
add_interface_port conduit_end UART_TXD export Output 1
add_interface_port conduit_end VGA_BLANK export Output 1
add_interface_port conduit_end VGA_CLK export Output 1
add_interface_port conduit_end VGA_HS export Output 1
add_interface_port conduit_end VGA_SYNC export Output 1
add_interface_port conduit_end VGA_VS export Output 1

